services:
  app:
    build: .
    environment:
      API_KEY: ${API_KEY}
    ports:
      - 8080:8080
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 21
      POSTGRES_DB: javabase
