services:
  app:
    build: .
    environment:
      API_KEY: ${API_KEY}
      DB_URL: postgresql://postgres:5432/javabase
      DB_USER: postgres
      DB_PASSWORD: 21
    ports:
      - 8080:8080
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 21
      POSTGRES_DB: javabase
